### ISSUE TITLE
Unsupported error handling.

### ISSUE THREAD

**Issue by vladyslav-dotsenko** [TotenDev/Function-Queue#1]
There is a problem with error handling.

```
try {
    queue.push(function(){
        throw new Error();
    })
} catch {
    condole.log('Oops!');
}
```

This code won't work and try..catch blocks are useless with this module.

**Comment by gwdp** [comment]
Hi! 

There is a synchronism problem with your code since `function-queue` does work asynchronous..

Javascript try catch blocks don't catch an exception that happened after that block, because the catch block is running on main scope before the queued code runs..

Something like that would work:

```
queue.push(function(){
    try {
        throw new Error();
    } catch {
        console.log('Oops!');
    }
})
```
